---

- paw: deathstar$darthvader
  group: simulation
  os: windows
  location: C:\Users\Public
  executors:
    - pwsh
    - psh

- paw: xwing$redleader
  group: simulation
  os: darwin
  location: /tmp
  executors:
    - sh

- paw: millenniumfalcon$hansolo
  group: simulation
  os: linux
  location: /tmp
  executors:
    - sh
