---

- paw: deathstar$darthvader
  enabled: 1
  group: simulation
  os: windows
  location: C:\Users\Public
  executors:
    - pwsh
    - psh

- paw: vwing$emperor
  enabled: 0
  group: simulation
  os: windows
  location: C:\Users\Public
  executors:
    - psh

- paw: xwing$redleader
  enabled: 1
  group: simulation
  os: darwin
  location: /tmp
  executors:
    - sh

- paw: millenniumfalcon$hansolo
  enabled: 1
  group: simulation
  os: linux
  location: /tmp
  executors:
    - sh
